### ISSUE TITLE
Hey Danny nice to see you development

### ISSUE THREAD

**Issue by carlosedubarreto** [Danny-Dasilva/Blender_Mediapipe#1]
Hello Danny.

I got a friend that sent me the link for your repository.

I felt that I knew that names from some place lol.

Hope you can keep on developing it and if I can help you on something, please just ask.

The code is confusing because I didn't spent too much time on it, as i did it only because a friend asked to.

But i don't like the lack of precision of mediapipe

**Comment by Danny-Dasilva** [comment]
Hey Carlos big fan! I've been following you on twitter for a while now. This repo is mostly a testing grounds as I figure out multi cam integration to hopefully make mediapipe more stable/consistent. I'm using blender to visualize 3d coordinate space as I figure out how to map between camera instances. 

I think the greatest benefit mediapipe has compared to some of the other solutions you're testing is it's face mesh model. A well rigged model plus [tension maps](https://twitter.com/cjones3D/status/1361657532108840962?s=20) could provide incredibly realistic real time results using Eevee or the new cyclesX.  Once I figure out multi-cam mapping I might experiment with that. But for the most part I agree, for full body mocap mediapipe is not sufficient.

**Comment by carlosedubarreto** [comment]
Fan? LOL, I didnt do much, most of the work were done by others 😊

well, i tried the multicam on mediapipe and gave up, this configuration was too complex to me.

You could try to dig the Easymocap github, the have multicam setup that I actualy was able to use, and then you could do a mixture from easymocap and mediapipe.

there is also another github with mediapie coda that does multicam. but i was not able to make it work.

Ill try to find it and send the link to you

**Comment by carlosedubarreto** [comment]
found it.

https://github.com/ntu-rris/google-mediapipe#7-triangulate-points

good luck

**Comment by Danny-Dasilva** [comment]
Thanks
